version: '3.3'
services:
  app:
    container_name: nestjs_api_${NODE_ENV}
    image: nestjs-api-local:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
      - 9229:${PORT}
    env_file:
      - .env
    networks:
      - nesjs-network
    depends_on:
      - oversee-mongo-local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  oversee-mongo-local:
    image: mongo:latest
    container_name: oversee_mongo_local
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db/dump:/db/dump
      - ./db/:/docker-entrypoint-initdb.d/:ro
    networks:
      - nesjs-network
    restart: always

networks:
  nesjs-network:
    driver: bridge
