version: '3.3'
services:
  app:
    container_name: nestjs_api_${NODE_ENV}
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
